services:
  app:
    container_name: suivi-bourse-app
    depends_on:
    - prometheus
    environment:
    - SB_SCRAPING_INTERVAL=${SCRAPING_INTERVAL}
    image: ghcr.io/pbrissaud/suivi-bourse-app:latest
    restart: unless-stopped
    volumes:
    - ./config.yaml:/home/appuser/.config/SuiviBourse/config.yaml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  grafana:
    container_name: suivi-bourse-graf
    depends_on:
    - prometheus
    image: grafana/grafana:11.2.2
    ports:
    - 3000:3000
    restart: unless-stopped
    volumes:
    - sb_grafana_data:/var/lib/grafana
    - ./grafana_provisioning:/etc/grafana/provisioning
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --storage.tsdb.retention.time=20y
    container_name: suivi-bourse-prom
    image: prom/prometheus:v2.54.1
    ports:
    - 9090:9090
    restart: unless-stopped
    volumes:
    - sb_prometheus_data:/prometheus
    - ./prometheus_provisioning:/etc/prometheus/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
#version: '3.8'
volumes:
  sb_prometheus_data:
    driver: local
  sb_grafana_data:
    driver: local
