{
 "title": "Stock share monitoring V5",
 "description": "Watch the price of the stock shares you own. For more detail : https://github.com/pbrissaud/suivi-bourse-app",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "share",
    "label": "Share",
    "query": {
     "query": "label_values(sb_share_info{quote_type=~\"$quote_type\", share_exchange=~\"$exchange\"},share_name)"
    }
   },
   {
    "name": "quote_type",
    "label": "Quote Type",
    "query": {
     "query": "label_values(sb_share_info, quote_type)"
    }
   },
   {
    "name": "exchange",
    "label": "Exchange",
    "query": {
     "query": "label_values(sb_share_info, share_exchange)"
    }
   },
   { "name": "DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sb_purchased_price{share_name=~\"$share\"} * on(share_name) sb_purchased_quantity{share_name=~\"$share\"})",
     "legendFormat": "Total Investment"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sb_share_price{share_name=~\"$share\"} * on(share_name) sb_owned_quantity{share_name=~\"$share\"})",
     "legendFormat": "Total Market Value"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sb_share_price{share_name=~\"$share\"} * on(share_name) sb_owned_quantity{share_name=~\"$share\"}) - sum(sb_purchased_price{share_name=~\"$share\"} * on(share_name) sb_purchased_quantity{share_name=~\"$share\"})",
     "legendFormat": "Current ROI"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sb_share_price{share_name=~\"$share\"} * on(share_name) sb_owned_quantity{share_name=~\"$share\"}) / sum(sb_purchased_price{share_name=~\"$share\"} * on(share_name) sb_purchased_quantity{share_name=~\"$share\"})",
     "legendFormat": "Improvement From Base"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(sb_share_price{share_name=~\"$share\"} * on(share_name) sb_owned_quantity{share_name=~\"$share\"}) - sum(sb_purchased_price{share_name=~\"$share\"} * on(share_name) sb_purchased_quantity{share_name=~\"$share\"})) + sum(sb_received_dividend{share_name=~\"$share\"})) / sum(sb_purchased_price{share_name=~\"$share\"} * on(share_name) sb_purchased_quantity{share_name=~\"$share\"})",
     "legendFormat": "Total Performance"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sb_share_price{share_name=~\"$share\"})",
     "legendFormat": "{{share_name}}"
    }
   ]
  },
  {
   "title": "$share",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "share",
   "targets": [
    {}
   ]
  },
  {
   "title": "Share price evolution",
   "type": "candlestick",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "last_over_time(sb_share_price{share_name=\"$share\"}[$__rate_interval])",
     "legendFormat": "close"
    },
    {
     "expr": "max_over_time(sb_share_price{share_name=\"$share\"}[$__rate_interval])",
     "legendFormat": "max"
    },
    {
     "expr": "min_over_time(sb_share_price{share_name=\"$share\"}[$__rate_interval])",
     "legendFormat": "min"
    },
    {
     "expr": "last_over_time(sb_share_price{share_name=\"$share\"}[$__rate_interval] offset $__rate_interval) ",
     "legendFormat": "open"
    }
   ]
  },
  {
   "title": "Purchased quantity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb_purchased_quantity{share_name=\"$share\"}"
    }
   ]
  },
  {
   "title": "Cost price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb_purchased_price{share_name=\"$share\"}"
    }
   ]
  },
  {
   "title": "Base",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sb_purchased_price{share_name=\"$share\"} * sb_purchased_quantity{share_name=\"$share\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Share Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sb_share_price{share_name=~\"$share\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Market Value",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sb_share_price{share_name=~\"$share\"} * on(share_name) sb_owned_quantity{share_name=~\"$share\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unitary Gain / Loss ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sb_share_price{share_name=~\"$share\"}) - sum(sb_purchased_price{share_name=~\"$share\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Owned quantity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb_owned_quantity{share_name=\"$share\"}"
    }
   ]
  },
  {
   "title": "Received dividend",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb_received_dividend{share_name=\"$share\"}"
    }
   ]
  },
  {
   "title": "Total gain / loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sb_share_price{share_name=~\"$share\"} * on(share_name) sb_owned_quantity{share_name=~\"$share\"}) - sum(sb_purchased_price{share_name=~\"$share\"} * on(share_name) sb_purchased_quantity{share_name=~\"$share\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}