name: "Create a new release"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 1-7 * 6"

permissions:
  contents: write
  pull-requests: write
  
jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.TOKEN }}"
      GITHUB_BRANCH: "master"
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: simple